stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-docker:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t ppl:latest .
  only:
    - main

test-job:
  stage: test
  script:
    - docker run --rm ppl:latest pytest .
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - main